<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/VASPLatformServiceBus/BS.DB.Social.Check/CallVasPlatform" name="CallVasPlatform-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="CallVasPlatform.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/VASPLatformServiceBus/BS.DB.Social.Check/CallVasPlatform"/>
    <wsdl:binding name="CallVasPlatform_ptt-binding" type="cal:CallVasPlatform_ptt" xmlns:cal="http://xmlns.oracle.com/pcbpel/adapter/db/VASPLatformServiceBus/BS.DB.Social.Check/CallVasPlatform">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="CallVasPlatform">
            <soap:operation soapAction="CallVasPlatform"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>