<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0"
                xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction"
                xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction"
                xmlns:ns0="http://vasplatform.mobifone.vn"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions"
                xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction"
                xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/sp/DBVasPlatform"
                exclude-result-prefixes="xsd oracle-xsl-mapper xsi xsl ns0 tns UUIDUserFunction IsUserInGroupFunction oraext IsUserInRoleFunction xp20 DVMFunctions oraxsl RuntimeTypeConversionFunctions XrefFunctions BasicCredentialsUserFunction">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="XSD">
        <oracle-xsl-mapper:schema location="../Schemas/NEOFormat.xsd"/>
        <oracle-xsl-mapper:rootElement name="request" namespace="http://vasplatform.mobifone.vn"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="XSD">
        <oracle-xsl-mapper:schema location="../Resources/DBVasPlatform_sp.xsd"/>
        <oracle-xsl-mapper:rootElement name="InputParameters"
                                       namespace="http://xmlns.oracle.com/pcbpel/adapter/db/sp/DBVasPlatform"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.3.0(XSLT Build 170820.1700.2557) AT [FRI NOV 29 11:04:19 ICT 2019].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <tns:InputParameters>
      <tns:P_SERVICE_ID>
        <xsl:value-of select="/ns0:request/ns0:Parameters/ns0:Parameter[ns0:name = 'SERVICE_ID']/ns0:value"/>
      </tns:P_SERVICE_ID>
      <tns:P_PKG_ID>
        <xsl:value-of select="/ns0:request/ns0:Parameters/ns0:Parameter[ns0:name = 'PKG_ID']/ns0:value"/>
      </tns:P_PKG_ID>
      <tns:P_MSISDN>
        <xsl:value-of select="/ns0:request/ns0:Parameters/ns0:Parameter[ns0:name = 'MSISDN']/ns0:value"/>
      </tns:P_MSISDN>
      <tns:P_SUB_ID>
        <xsl:value-of select="/ns0:request/ns0:Parameters/ns0:Parameter[ns0:name = 'SUB_ID']/ns0:value"/>
      </tns:P_SUB_ID>
      <tns:P_REG_DATE>
        <xsl:value-of select="/ns0:request/ns0:Parameters/ns0:Parameter[ns0:name = 'REG_DATE']/ns0:value"/>
      </tns:P_REG_DATE>
      <tns:P_CHANNEL>
        <xsl:value-of select="/ns0:request/ns0:Parameters/ns0:Parameter[ns0:name = 'CHANNEL']/ns0:value"/>
      </tns:P_CHANNEL>
      <tns:P_NUM_REG>
        <xsl:value-of select="/ns0:request/ns0:Parameters/ns0:Parameter[ns0:name = 'NUM_REG']/ns0:value"/>
      </tns:P_NUM_REG>
      <tns:P_STATE>
        <xsl:value-of select="/ns0:request/ns0:Parameters/ns0:Parameter[ns0:name = 'STATE']/ns0:value"/>
      </tns:P_STATE>
      <tns:P_IS_EXTEND>
        <xsl:value-of select="/ns0:request/ns0:Parameters/ns0:Parameter[ns0:name = 'IS_EXTEND']/ns0:value"/>
      </tns:P_IS_EXTEND>
      <tns:P_START_DATE>
        <xsl:value-of select="/ns0:request/ns0:Parameters/ns0:Parameter[ns0:name = 'START_DATE']/ns0:value"/>
      </tns:P_START_DATE>
      <tns:P_END_DATE>
        <xsl:value-of select="/ns0:request/ns0:Parameters/ns0:Parameter[ns0:name = 'END_DATE']/ns0:value"/>
      </tns:P_END_DATE>
      <tns:P_NEXT_EXTEND>
        <xsl:value-of select="/ns0:request/ns0:Parameters/ns0:Parameter[ns0:name = 'NEXT_EXTEND']/ns0:value"/>
      </tns:P_NEXT_EXTEND>
      <tns:P_PKG>
        <xsl:value-of select="/ns0:request/ns0:Parameters/ns0:Parameter[ns0:name = 'PKG']/ns0:value"/>
      </tns:P_PKG>
      <tns:P_NUM_FREE>
        <xsl:value-of select="/ns0:request/ns0:Parameters/ns0:Parameter[ns0:name = 'NUM_FREE']/ns0:value"/>
      </tns:P_NUM_FREE>
      <tns:P_PKG_CK>
        <xsl:value-of select="/ns0:request/ns0:Parameters/ns0:Parameter[ns0:name = 'PKG_CK']/ns0:value"/>
      </tns:P_PKG_CK>
      <tns:P_PROG_ID>
        <xsl:value-of select="/ns0:request/ns0:Parameters/ns0:Parameter[ns0:name = 'PROG_ID']/ns0:value"/>
      </tns:P_PROG_ID>
      <tns:P_LAST_UPDATE>
        <xsl:value-of select="/ns0:request/ns0:Parameters/ns0:Parameter[ns0:name = 'LAST_UPDATE']/ns0:value"/>
      </tns:P_LAST_UPDATE>
      <tns:P_PRICE>
        <xsl:value-of select="/ns0:request/ns0:Parameters/ns0:Parameter[ns0:name = 'PRICE']/ns0:value"/>
      </tns:P_PRICE>
      <tns:P_LAST_EXTEND>
        <xsl:value-of select="/ns0:request/ns0:Parameters/ns0:Parameter[ns0:name = 'LAST_EXTEND']/ns0:value"/>
      </tns:P_LAST_EXTEND>
      <tns:P_FIRST_TIME>
        <xsl:value-of select="/ns0:request/ns0:Parameters/ns0:Parameter[ns0:name = 'FIRST_TIME']/ns0:value"/>
      </tns:P_FIRST_TIME>
    </tns:InputParameters>
  </xsl:template>
</xsl:stylesheet>
