<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction" xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction" xmlns:ns0="http://vasplatform.mobifone.vn" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions" xmlns:tns="urn:click2Call" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions" xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns UUIDUserFunction IsUserInGroupFunction oraext IsUserInRoleFunction xp20 DVMFunctions oraxsl RuntimeTypeConversionFunctions XrefFunctions BasicCredentialsUserFunction">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="XSD">
            <oracle-xsl-mapper:schema location="../Schemas/NEOFormat.xsd"/>
            <oracle-xsl-mapper:rootElement name="request" namespace="http://vasplatform.mobifone.vn"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="XSD">
            <oracle-xsl-mapper:schema location="../Schemas/IVR.xsd"/>
            <oracle-xsl-mapper:rootElement name="MakeOutgoingCall" namespace="urn:click2Call"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.3.0(XSLT Build 170820.1700.2557) AT [WED DEC 11 01:12:30 ICT 2019].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <tns:MakeOutgoingCall>
         <tns:REQ_TYPE>
            <xsl:value-of select="/ns0:request/ns0:Parameters/ns0:Parameter[ns0:name = 'REQ_TYPE']/ns0:value"/>
         </tns:REQ_TYPE>
         <tns:CALL_ID>
            <xsl:value-of select="/ns0:request/ns0:Parameters/ns0:Parameter[ns0:name = 'CALL_ID']/ns0:value"/>
         </tns:CALL_ID>
         <tns:LEG1_NUMBER>
            <xsl:value-of select="/ns0:request/ns0:Parameters/ns0:Parameter[ns0:name = 'LEG1_NUMBER']/ns0:value"/>
         </tns:LEG1_NUMBER>
         <tns:LEG2_NUMBER>
            <xsl:value-of select="/ns0:request/ns0:Parameters/ns0:Parameter[ns0:name = 'LEG2_NUMBER']/ns0:value"/>
         </tns:LEG2_NUMBER>
         <tns:SERVICE_NOTIFY_CALLBACK>
            <xsl:value-of select="/ns0:request/ns0:Parameters/ns0:Parameter[ns0:name = 'SERVICE_NOTIFY_CALLBACK']/ns0:value"/>
         </tns:SERVICE_NOTIFY_CALLBACK>
         <tns:CP_SP_NAME>
            <xsl:value-of select="/ns0:request/ns0:Parameters/ns0:Parameter[ns0:name = 'CP_SP_NAME']/ns0:value"/>
         </tns:CP_SP_NAME>
         <tns:CAMPAIGN_NAME>
            <xsl:value-of select="/ns0:request/ns0:Parameters/ns0:Parameter[ns0:name = 'CAMPAIGN_NAME']/ns0:value"/>
         </tns:CAMPAIGN_NAME>
         <tns:ANSWER_TIMEOUT>
            <xsl:value-of select="/ns0:request/ns0:Parameters/ns0:Parameter[ns0:name = 'ANSWER_TIMEOUT']/ns0:value"/>
         </tns:ANSWER_TIMEOUT>
      </tns:MakeOutgoingCall>
   </xsl:template>
</xsl:stylesheet>
