<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/sp/SendSMSMTLater" xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction" xmlns:ns0="http://vasplatform.mobifone.vn" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions" xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns UUIDUserFunction IsUserInGroupFunction oraext IsUserInRoleFunction xp20 DVMFunctions oraxsl RuntimeTypeConversionFunctions XrefFunctions BasicCredentialsUserFunction">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="XSD">
            <oracle-xsl-mapper:schema location="../Schemas/NEOFormat.xsd"/>
            <oracle-xsl-mapper:rootElement name="request" namespace="http://vasplatform.mobifone.vn"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="XSD">
            <oracle-xsl-mapper:schema location="../Resources/SendSMSMTLater_sp.xsd"/>
            <oracle-xsl-mapper:rootElement name="InputParameters" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/sp/SendSMSMTLater"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.3.0(XSLT Build 170820.1700.2557) AT [SUN DEC 22 17:27:23 ICT 2019].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <tns:InputParameters>
         <tns:P_SERVICE_CODE>
            <xsl:value-of select="/ns0:request/ns0:Parameters/ns0:Parameter[ns0:name = 'SERVICE_CODE']/ns0:value"/>
         </tns:P_SERVICE_CODE>
         <tns:P_MSISDN>
            <xsl:value-of select="/ns0:request/ns0:Parameters/ns0:Parameter[ns0:name = 'MSISDN']/ns0:value"/>
         </tns:P_MSISDN>
         <tns:P_BRANDNAME>
            <xsl:value-of select="/ns0:request/ns0:Parameters/ns0:Parameter[ns0:name = 'BRANDNAME']/ns0:value"/>
         </tns:P_BRANDNAME>
         <tns:P_CHANNEL>
            <xsl:value-of select="/ns0:request/ns0:Parameters/ns0:Parameter[ns0:name = 'CHANNEL']/ns0:value"/>
         </tns:P_CHANNEL>
         <tns:P_CONTENT>
            <xsl:value-of select="/ns0:request/ns0:Parameters/ns0:Parameter[ns0:name = 'CONTENT']/ns0:value"/>
         </tns:P_CONTENT>
         <tns:P_DA>
            <xsl:value-of select="/ns0:request/ns0:Parameters/ns0:Parameter[ns0:name = 'DA']/ns0:value"/>
         </tns:P_DA>
         <tns:P_TYPE>
            <xsl:value-of select="/ns0:request/ns0:Parameters/ns0:Parameter[ns0:name = 'TYPE']/ns0:value"/>
         </tns:P_TYPE>
         <tns:P_VALUE>
            <xsl:value-of select="/ns0:request/ns0:Parameters/ns0:Parameter[ns0:name = 'VALUE']/ns0:value"/>
         </tns:P_VALUE>
         <tns:P_SESSION>
            <xsl:value-of select="/ns0:request/ns0:Parameters/ns0:Parameter[ns0:name = 'SESSION']/ns0:value"/>
         </tns:P_SESSION>
      </tns:InputParameters>
   </xsl:template>
</xsl:stylesheet>
