<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0"
                xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction"
                xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction"
                xmlns:tns="http://vasplatform.mobifone.vn"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions"
                xmlns:ns0="urn:click2Call" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions"
                xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction"
                exclude-result-prefixes="xsd oracle-xsl-mapper xsi xsl ns0 tns UUIDUserFunction IsUserInGroupFunction oraext IsUserInRoleFunction xp20 DVMFunctions oraxsl RuntimeTypeConversionFunctions XrefFunctions BasicCredentialsUserFunction">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="XSD">
        <oracle-xsl-mapper:schema location="../Schemas/IVR.xsd"/>
        <oracle-xsl-mapper:rootElement name="MakeOutgoingCallResponse" namespace="urn:click2Call"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="XSD">
        <oracle-xsl-mapper:schema location="../Schemas/BS_IVR.xsd"/>
        <oracle-xsl-mapper:rootElement name="response" namespace="http://vasplatform.mobifone.vn"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.3.0(XSLT Build 170820.1700.2557) AT [FRI NOV 08 15:22:43 ICT 2019].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
  <xsl:variable name="v_item" select="/*:Body/*:MakeOutgoingCallResponse/*:return/*:item"/>
    <tns:response>
      <tns:STATUS>
        <xsl:value-of select="'0'"/>
      </tns:STATUS>
      <tns:STATUS_MESSAGE>
        <xsl:value-of select="'SUCCESS'"/>
      </tns:STATUS_MESSAGE>
      <tns:Parameters>
        <xsl:for-each select="$v_item">
          <tns:Parameter>
            <tns:name>
              <xsl:value-of select="concat('CALL_ID_', position())"/>
            </tns:name>
            <tns:name>
              <xsl:value-of select="$v_item[position()]/*:call_id"/>
            </tns:name>
          </tns:Parameter>
          <tns:Parameter>
            <tns:name>
              <xsl:value-of select="concat('RESULTCODE_', position())"/>
            </tns:name>
            <tns:name>
              <xsl:value-of select="$v_item[position()]/*:resultcode"/>
            </tns:name>
          </tns:Parameter>
          <tns:Parameter>
            <tns:name>
              <xsl:value-of select="concat('RESULTDESC_', position())"/>
            </tns:name>
            <tns:name>
              <xsl:value-of select="$v_item[position()]/*:resultdesc"/>
            </tns:name>
          </tns:Parameter>
        </xsl:for-each>
      </tns:Parameters>
    </tns:response>
  </xsl:template>
</xsl:stylesheet>
