<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/socket/VASPLatformServiceBus/DemoSocketClient/socketReference"
                  name="socketReference-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                  xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <wsdl:import location="socketReference.wsdl"
               namespace="http://xmlns.oracle.com/pcbpel/adapter/socket/VASPLatformServiceBus/DemoSocketClient/socketReference"/>
  <wsdl:binding name="OutboundRequestReply_ptt-binding" type="soc:OutboundRequestReply_ptt"
                xmlns:soc="http://xmlns.oracle.com/pcbpel/adapter/socket/VASPLatformServiceBus/DemoSocketClient/socketReference">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <wsdl:operation name="OutboundRequestReply">
      <soap:operation soapAction="OutboundRequestReply"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
</wsdl:definitions>